apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: iac-instance-ec2
  namespace: flux-system
spec:
  path: ./
  approvePlan: "plan-main-a12a03067d"
  destroyResourcesOnDeletion: true
  interval: 5s
  sourceRef:
    kind: GitRepository
    name: iac-instance-ec2
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-credentials